services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${DBUSERID}
      POSTGRES_PASSWORD: ${DBPASSWORD}
      POSTGRES_DB: ${DBDATABASE}
    volumes:
      - ./sqlserverdata:/var/lib/postgresql/data
    networks:
      - cocktail-net
    restart: always

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - wwwroot:/src/wwwroot
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=${DBSERVER};Port=${DBPORT};Database=${DBDATABASE};Username=${DBUSERID};Password=${DBPASSWORD};
      - Jwt__Key=${JWTKEY}
      - Jwt__Issuer=${JWTISSUER}
      - Jwt__Audience=${JWTAUDIENCE}
      - Authentication__Google__ClientId=${GOOGLECLIENTID}
      - Authentication__Google__ClientSecret=${GOOGLECLIENTSECRET}
      - GOOGLE_MAPS_API_KEY=${GOOGLEAPIKEY}
    working_dir: /src
    depends_on:
      - db
    networks:
      - cocktail-net
    restart: always
    # Encrypt=False;TrustServerCertificate=True

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    working_dir: /app
    command: npm run start -- --host 0.0.0.0
    depends_on:
      - backend
    networks:
      - cocktail-net
    restart: always

  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: nginx
    volumes:
      - wwwroot:/app/wwwroot
    ports:
      - "8081:80"
    depends_on:
      - frontend
      - backend
    networks:
      - cocktail-net
    restart: always

volumes:
  sqlserverdata:

  wwwroot:
  

networks:
  cocktail-net:
    driver: bridge
