-- SELECT * FROM AspNetUsers;
-- GO

-- DROP DATABASE [sqlserverdata];
-- 

-- SELECT TABLE_NAME
-- FROM INFORMATION_SCHEMA.TABLES
-- WHERE TABLE_TYPE = 'BASE TABLE';

-- SELECT DB_NAME() AS CurrentDatabase;

-- SELECT COLUMN_NAME, DATA_TYPE
-- FROM INFORMATION_SCHEMA.COLUMNS
-- WHERE TABLE_NAME = 'Reviews'



